version: "3"

tasks:
  web:start:
    desc: Start main frontend web app in development mode
    dir: frontend/dashboard
    cmds:
      - yarn dev

  dashboard:start:
    desc: Start web dashboard in development mode
    dir: frontend/dashboard
    cmds:
      - yarn dev

  service-api:start:
    desc: Start backend service-api in development mode
    dir: backend/servce-api
    cmds:
      - go run main.go

  docker-compose:up:
    desc: Start docker-compose for development mode
    dir: devops
    cmds:
      - docker-compose up -d

  docker-compose:down:
    desc: Stop and clean docker-compose (*use this will remove all persistance data from volume)
    dir: devops
    cmds:
      - docker-compose down -v

  docker-compose:restart:
    desc: Restart cotainer in docker-compose
    dir: devops
    cmds:
      - docker-compose restart

  docker-compose:status:
    desc: Get status of container in docker-compose
    dir: devops
    cmds:
      - docker-compose ps -a

  terraform:init:
    desc: Initial terraform
    dir: devops/terraform
    cmds:
      - terraform init

  terraform:apply:
    desc: Apply terraform
    dir: devops/terraform
    cmds:
      - terraform apply
